# Generated by Django 4.0.3 on 2022-03-11 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=25, verbose_name='Nom')),
                ('email', models.EmailField(error_messages={'unique': 'A client with that email address already exists.'}, max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(error_messages={'unique': 'A client with that phone number already exists.'}, max_length=20, unique=True, verbose_name='numero de telephone')),
                ('mobile', models.CharField(error_messages={'unique': 'A client with that mobile number already exists.'}, max_length=20, unique=True, verbose_name='numero de portable')),
                ('company_name', models.CharField(max_length=250, verbose_name="nom d'entreprise")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree a')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis a jour a')),
                ('sales_contact', models.ForeignKey(error_messages={'limit_choices_to': 'This user is not part of the sales team.'}, limit_choices_to={'role': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='contact commercial')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
